### ISSUE TITLE
 Can it support connect a display screen with HDMI?

### ISSUE THREAD

**Issue by jay763190097** [dizhenhuoshan/XiaoMiGaming-8th-Hackintosh#1]

**Comment by jay763190097** [comment]
I already bought a type-c to hdmi cable solve the problem.

**Comment by dizhenhuoshan** [comment]
Not possible. This laptop's HDMI is directly connected to dGPU (Nvidia). You can verify this by disabling nvidia GPU and then the HDMI will not work even in Windows :)
